/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React, {Component} from 'react';
import {Platform, StyleSheet, Text, View, TouchableOpacity} from 'react-native';
import ErxesSdk from 'react-native-erxes-sdk';

export default class App extends Component {
  componentDidMount() {
    //https://api.office.erxes.io
    //gumQ2P
    ErxesSdk.init('https://api.office.erxes.io', 'gumQ2P');
    // ErxesLibrary.init('https://testingbro.app.erxes.io/', 'CRxbqw');
    // ErxesLibrary.initSaas('testingbro', 'CRxbqw');
    // ErxesLibrary.initSaas(argum)
    // testingbro
    // https://testingbro.app.erxes.io/api/
  }
  go = () => {
    ErxesSdk.start();
  };

  render() {
    return (
      <View style={styles.container}>
        <TouchableOpacity
          onPress={() => {
            this.go();
          }}>
          <Text style={styles.welcome}>Test it</Text>
        </TouchableOpacity>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});
