/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React, { Component } from 'react';
import {
  Platform,
  StyleSheet,
  Text,
  View,
  TouchableOpacity,
  Button,
} from 'react-native';
import ErxesSdk from 'react-native-erxes-sdk';

export default class App extends Component {
  componentDidMount() {}
  test = () => {
    ErxesSdk.init('apiHost', 'branCode');

    ErxesSdk.start();
  };

  testWithData = () => {
    ErxesSdk.init('apiHost', 'branCode');
    let custom = { email: 'example@gmail.com', other: 'otherTest' };

    ErxesSdk.startWithData(JSON.stringify(custom));
  };

  render() {
    return (
      <View style={styles.container}>
        <View style={{ marginBottom: 20 }}>
          <Button
            title="Test it"
            onPress={() => {
              this.test();
            }}
          />
        </View>
        <Button
          title="Test it with customData"
          onPress={() => {
            this.testWithData();
          }}
        />
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'white',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});
